spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.transaction.support: TRACE